version: "3.7"

services:
  db:
    image: postgres:13.3
    # restart: always
    container_name: tgbot_db
    environment:
      POSTGRES_USER: "tgbot_admin"
      POSTGRES_PASSWORD: "permiSs10N_GrANt3D"
      POSTGRES_HOST_AUTH_METHOD: "trust"
    volumes:
      - tgbot_data:/var/lib/postgresql/data
      - ./init_db.sh:/docker-entrypoint-initdb.d/tgbot_init_db.sh
  
  tgbot:
    build: .
    container_name: tgbot
    # restart: always
    command: 'node tgbot.js'

volumes:
  tgbot_data:
    driver: local